server:
  servlet:
    context-path: /cluster
  port: 8043

### 自定义配置文件
spring:
    redis:
      #redis节点密码
      password: 123
      #数据库索引（集群只有0号数据库）
      database: 0
      #连接池的配置（根据需要可以换成jedis）
      lettuce:
        pool:
          #连接池的最大连接数（默认是8）
          max-active: 8
          #连接池的最大空闲连接数（默认是8）
          max-idle: 8
          #最小空闲连接数（默认是0）
          min-idle: 0
      host: 192.168.14.104


