server:
  servlet:
    context-path: /cluster
  port: 8043

### 自定义配置文件
spring:
    redis:
      #redis节点密码
      password: 123
      #数据库索引（集群只有0号数据库）
      database: 0
      #集群配置
      cluster:
        nodes:
          - 192.168.14.101:6379
          - 192.168.14.102:6380
          - 192.168.14.103:6381
          - 192.168.14.101:6382
          - 192.168.14.102:6383
          - 192.168.14.103:6384
      #连接池的配置（根据需要可以换成jedis）
      lettuce:
        pool:
          #连接池的最大连接数（默认是8）
          max-active: 8
          #连接池的最大空闲连接数（默认是8）
          max-idle: 8
          #最小空闲连接数（默认是0）
          min-idle: 0


